### ISSUE TITLE
Signing a Document Hash

### ISSUE THREAD

**Issue by dmitriy-shleht** [ctt-gob-es/FirmaXadesNet45#5]
Is it possible to sign a document hash? so that the signature was separate from the data.
Does this violate the XADES standard?

**Comment by dnturbanismo** [comment]
If you set the SignaturePackaging property to HASH_INTERNALLY_DETACHED you will get a XAdES internally detached signature, but the signed content will be the SHA-256 hash of your document. This signature type is XAdES compliant but keep in mind that a signature validator will not check the original document hash because doesn't know that content you are signing it's a document hash, for this reason the validation always will be successfully.

Other way it's to sign a manifest thats contains the references to your content, but this feature is not supported by the library.

**Comment by dmitriy-shleht** [comment]
I think this will suit me.
Thank You!
